name: tests

on:
  pull_request:
    paths-ignore:
      - docs/**
    branches-ignore:
      - none

  push:
    branches: ["main"]
    paths-ignore: ["docs/**"]

jobs:
  test:
    name: run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v2

      - name: Run tests
        run: make test
